services:
  api:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_JDBCURL=jdbc:postgresql://postgres:5432/postgres
    depends_on:
      - postgres
    expose:
      - "8080"

  postgres:
    container_name: postgres-levo-pra-voce
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    expose:
      - "5432"

volumes:
  postgres-data:
    name: postgres-data
    driver: local