logging:
  file:
    name: /tmp/logs/spring-boot-logging.log
  level:
    root: debug

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
  web:
    resources:
      add-mappings: false
  flyway:
    schemas: public
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: levopravoceoficial@gmail.com
    password: crlebwntrciljate
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: tnKVXNLyr7TotnKVXNLyr7TotnKVXNLyr7TotnKVXNLyr7TotnKVXNLyr7TotnKVXNLyr7TotnKVXNLyr7TotnKVXNLyr7TotnKVXNLyr7TotnKVXNLyr7TotnKVXNLyr7TotnKVXNLyr7To

google:
  map:
    api:
      key: AIzaSyDLUo_Xks5VkIA9XU_tn__vE99L1p8tsWY

server:
  port: 8888
