spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
  web:
    resources:
      add-mappings: false
  flyway:
    schemas: public
    baseline-on-migrate: true
jwt:
  secret: tn*KVXNLyr7To*VVhuffe!T223iE3e^qns^E^Mf

server:
  port: 8888
